export const SET_ERROR_MESSAGE = "SET_ERROR_MESSAGE";
export const REGISTER_START = "REGISTER_START";
export const REGISTER_END = "REGISTER_FAIL";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const SET_REGISTERED_START = "SET_REGISTERED_START";
export const SET_REGISTERED_END = "SET_REGISTERED_END";

export const AUTHENTICATE_START = "AUTHENTICATE_START";
export const AUTHENTICATE_END = "AUTHENTICATE_END";
export const AUTHENTICATE_FAIL = "AUTHENTICATE_FAIL";
export const ADD_FIRE_USER = "ADD_FIRE_USER";

export const LOGOUT = "LOGOUT";

export const EDIT_RECTANGULAR_MODAL_VISIBILITY = "EDIT_RECTANGULAR_MODAL_VISIBILITY";
export const SHOW_NEWPROJECT_MODAL = "SHOW_NEWPROJECT_MODAL";
export const HIDE_NEWPROJECT_MODAL = "HIDE_NEWPROJECT_MODAL";
export const EDIT_ROUND_MODAL_VISIBILITY = "EDIT_ROUND_MODAL_VISIBILITY";
export const EDIT_SAVE_CHECK_MODAL_VISIBILITY = "EDIT_SAVE_CHECK_MODAL_VISIBILITY";
